name: Continuous Delivery
on:
  # Can be un-commented once main branch is protected
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # linux/amd64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          # linux/arm64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
          # linux/arm/v7
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
          # linux/arm/v6
          - os: ubuntu-latest
            target: arm-unknown-linux-musleabihf
          # MacOS: Intel (TODO: add Apple Silicon once Big Sur is available)
          - os: macos-latest
            target: x86_64-apple-darwin
          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: stable
          override: true

      # With each cache weighing in at ~500MB per target,
      # and this repository maxing out at 5GB of caches,
      # it might make sense not to cache dependencies.
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Run dist
        run: cargo xtask dist ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: ./target/dist/
          if-no-files-found: error
          retention-days: 7

  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # linux/amd64
      - uses: actions/download-artifact@v2
        with:
          name: x86_64-unknown-linux-gnu
          path: target/dist
      
      # linux/arm64
      - uses: actions/download-artifact@v2
        with:
          name: aarch64-unknown-linux-musl
          path: target/dist

      # linux/arm/v7
      - uses: actions/download-artifact@v2
        with:
          name: armv7-unknown-linux-musleabihf
          path: target/dist

      # linux/arm/v6
      - uses: actions/download-artifact@v2
        with:
          name: arm-unknown-linux-musleabihf
          path: target/dist

      - name: Build and push
        run: cargo xtask docker build --push